[package]
name = "watchdog"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]
cli = ["dep:clap"]

[dev-dependencies]
tokio-test = "0.4.2"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.10", features = ["derive"], optional = true }
serde = { version = "1.0.164", features = ["derive"], optional = true }
tokio = { version = "1.28.2", features = ["full"] }
